require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'test/**/*'
    - 'lib/tasks/*.rake'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
