default: &default
  adapter: postgresql
  encoding: utf8
  ctype: ru_RU.UTF-8
  collation: ru_RU.UTF-8
  template: template0
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: book_swap_development
  host: localhost
  username: postgres
  password: mysecretpassword

test:
  <<: *default
  database: book_swap_test
  host: localhost
  username: postgres
  password: mysecretpassword

production:
  <<: *default
  database: book_swap_production
